version: "3"
services:
  shot-wayl-one:
    image: registry.wayl.one/shot-scraper-api
    ports:
      - 5000
    restart: always
    labels:
      kompose.service.expose: shotk.wayl.one
      kompose.image-pull-secret: regcred
