version: "3"
services:
  shot-wayl-one:
    image: registry.wayl.one/shot-scraper-api
    ports:
      - 5000
    environment:
      - ACCESS_KEY=7FkTVSd7ti1sXANgVZnD
      - SECRET_KEY=WDL6acr7GrMd9BVZGTECRVlahFbEDVZFYQtvxAm8
    restart: always
    labels:
      kompose.service.expose: shots.wayl.one, shots.k.waylonwalker.com
      # kompose.image-pull-secret: regcred
